### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by chase-moskal** [theZiggurat/gputoy#23]
hello, this project looks very interesting, and i was wondering if it will become available with a permissive license like mit?

🍻

**Comment by theZiggurat** [comment]
Hi Chase,
I am not too familiar with the legal side of open source. I'm not sure about redistribution because I don't see how that makes sense in the context of a website.  That being said, I will look into adding a license so others can contribute to project. I'm open to suggestions. Thanks!

**Comment by chase-moskal** [comment]
@theZiggurat 

i'd encourage you to make this tool free software :people_holding_hands: 

i like the classic [mit license](https://choosealicense.com/licenses/mit/).

if you like the simple terms in the license, to adpot it for this project, all you need to do, is paste the license text into a `license` file at the root of the project, and edit your name into the copyright line :beers: 

in terms of the program's output (shaders), i expect that it's defacto that such program outputs are free of licensing restrictions, not sure if an explicit notice is necessary :man_shrugging:

**Comment by theZiggurat** [comment]
project now licensed

**Comment by chase-moskal** [comment]
🥳🎉 awesome @theZiggurat !
